### PR TITLE
using both  --apply and --ignore flag

### LINKED ISSUE #363: using both `--apply` and `--ignore` flags should not be allowed
**Describe the bug**
Using both flags at the same time is not throwing any error

**To Reproduce**
Run the analyzer with this `vue-mess-detector.json`
```js
{
  "apply": "vue-essential,vue-recommended,vue-strong,rrd,security",
  "ignore": "multiAttributeElements,ifWithoutCurlyBraces"
}
```

1. What is the exact code you are analyzing?
-

3. What is the output you are getting?
Its being executed normally

**Expected behavior**
It should throw an error because both flags shouldnt be used at the same time

**Screenshots**
N/A

**Used version number of vue-mess-detector:** `0.57.0`

**Used version number of node & yarn:** -

**Additional context**
This was detected in this other [issue](https://github.com/rrd108/vue-mess-detector/issues/360)

### PR DESCRIPTION
**Pull request by rrd108**
### Summary
drop error when both  `--apply` and `--ignore` flags used

### Description
Somewere in the code changes we missed this, and the test case was not right, so the error remined hidden. Now cli flags and config file values are checked.

### Related Issues
Fixes #363 

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: src/helpers/checkArgs.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+/* eslint-disable node/prefer-global/process */
+import { BG_ERR, BG_RESET } from '../rules/asceeCodes'
+
+const checkArgs = (argv: string[], config: { apply?: any, ignore?: any }) => {
```
Comment (David-Pena) [inline src/helpers/checkArgs.ts:4]: I think you can use this `Config` type from the `/types/Config.ts` for the config parameter
```ts
export interface Config {
  path: string
  apply: string
  ignore: string
  exclude: string
  group: string
  level: string
  sort: string
  output: string
  override: OverrideConfig
  isDefault?: boolean
}
```

File: src/helpers/checkArgs.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+  const hasIgnore = argv.some(arg => arg.startsWith('--ignore') || arg.startsWith('-i'))
+  const hasApply = argv.some(arg => arg.startsWith('--apply') || arg.startsWith('-a'))
```
Comment (David-Pena) [inline src/helpers/checkArgs.ts:6]: I think the purpose of these lines is the same as this helper function `wasOptionPassed` from `/helpers/wasOptionPassed.ts`?

```ts
// Helper function to determine if an option was passed via CLI
export function wasOptionPassed(option: string) {
  // Regular expression to match the exact option with any value
  const regex = new RegExp(`--${option}(?:=[^\\s]*)?$`)

  // eslint-disable-next-line node/prefer-global/process
  return process.argv.some(arg => regex.test(arg))
}

```

If you think it doesnt apply, that helper function is not being used anymore so it should be deleted

**Review by David-Pena — COMMENTED** [review]
Please check out my comments 👀

**Review by David-Pena — APPROVED** [review]
