### PR TITLE
fix: add condition to check when both flags are applied

### LINKED ISSUE #193: use `apply` and `ignore` flags together
It should error out

### PR DESCRIPTION
**Pull request by David-Pena**
### Summary
Add the logic to check if `--apply` and `--ignore` are provided via CLI at the same time and fix the failing test.

### Description
- Add helper method `wasOptionPassed`
- Add object to keep track of `--apply` and `--ignore` flags in CLI and config file
- Update tests

### Related Issues
Parent #63 
Fixes #193 

### Type of Change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

### Screenshots (if applicable)
image

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -44,6 +45,10 @@ catch {
   output.push({ info: `👉 Using default configuration` })
 }
 
+// Check if `apply` or `ignore` options were explicitly passed
+const applyFromCLI = wasOptionPassed('apply')
```
Comment (rrd108) [inline src/index.ts:49]: What about when both apply and ignore are present in the config file?
Or apply in the config and ignore from cli?

Should not we fire this in all cases?

**Review by rrd108 — CHANGES_REQUESTED** [review]

File: src/index.ts (hunk 1 above)
Comment (David-Pena) [reply src/index.ts:49]: On it, I'll add more tests to check the behavior in those cases 👀

**Comment by David-Pena** [comment]
Finally this is ready to be reviewed again @rrd108 

I fix the validation to error out when any combination of apply/ignore is present (from CLI and/or config file)

**Review by rrd108 — APPROVED** [review]
